### ISSUE TITLE
Issue with generation of certificates

### ISSUE THREAD

**Issue by arnauddb** [JrCs/docker-letsencrypt-nginx-proxy-companion#341]
Hi,

I was recently unable to generate new certificates for my containers so I've stopped docker-letsencrypt-nginx-proxy-companion and remove the certificates in the certs folder and restarted it but now it doesn't work anly more.

I am getting the following error in the logs:
2018-03-05 07:47:37,344:ERROR:simp_le:1421: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If you haven't setup correct CAA fields or if your DNS provider does not support CAA, validation attempts after september 8, 2017 will fail.  Failing authorizations: ...

I didn't get this error before. Is there any changes in Let's Encrypt since last month ?
I've added a CCA field in the DNS of my server (OVH) to see if it fixes anything but it doesn't work.

Thanks for your help

**Comment by buchdag** [comment]
Hi. Please check the the failing authorizations URL returned by Let's Encrypt (in the containers logs) for additional informations on the reason LE couldn't validate the authorization. Be advised that it will contain your domain names, so don't post the URL here if you don't want your domain names to be made public.

**Comment by javierojeda94** [comment]
How do I interpret those url contents, @buchdag ? I'm facing this problem right now but I don't understand the json

**Comment by Egregors** [comment]
Exactly the same problem. Maybe this JSON will be useful:

```
{
  "identifier": {
    "type": "dns",
    "value": "---"
  },
  "status": "invalid",
  "expires": "2018-03-20T01:26:20Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/Hn_IErKZw1Jy960VkxmY7ZpCCshVkiVuV9Rd3ENHLkk/3796014745",
      "token": "-JSClA_ox94NI1bzJkADbxYLK8vkHtSeF6wwb8Abh9o"
    },
    {
      "type": "tls-sni-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/Hn_IErKZw1Jy960VkxmY7ZpCCshVkiVuV9Rd3ENHLkk/3796014747",
      "token": "Fi6T-2sgHvxOgv2w-RFNPZ5RTfNgAnj0kgGtrcfBMrU"
    },
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:acme:error:unauthorized",
        "detail": "Invalid response from http://---/.well-known/acme-challenge/rwA0TTTwVPNN0rG2Kc2W1HoxfDEgVxPT4t1r1PkGyVQ: \"\u003c!DOCTYPE html\n\u003e\n\u003chtml\u003e\n\u003chead\u003e\n\u003cmeta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\"/\u003e\n\u003ctitle\u003eYouTrack | 404 - объект не \"",
        "status": 403
      },
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/Hn_IErKZw1Jy960VkxmY7ZpCCshVkiVuV9Rd3ENHLkk/3796014748",
      "token": "rwA0TTTwVPNN0rG2Kc2W1HoxfDEgVxPT4t1r1PkGyVQ",
      "keyAuthorization": "rwA0TTTwVPNN0rG2Kc2W1HoxfDEgVxPT4t1r1PkGyVQ.qA3BJGXhMw7_WGi4eXnslOeZpI0L5za75Nrq_YSyLBQ",
      "validationRecord": [
        {
          "url": "https://---/.well-known/acme-challenge/rwA0TTTwVPNN0rG2Kc2W1HoxfDEgVxPT4t1r1PkGyVQ",
          "hostname": "---",
          "port": "443",
          "addressesResolved": [
            "-.-.-.-"
          ],
          "addressUsed": "-.-.-.-"
        },
        {
          "url": "http://---/.well-known/acme-challenge/rwA0TTTwVPNN0rG2Kc2W1HoxfDEgVxPT4t1r1PkGyVQ",
          "hostname": "---",
          "port": "80",
          "addressesResolved": [
            "-.-.-.-"
          ],
          "addressUsed": "-.-.-.-"
        }
      ]
    }
  ],
  "combinations": [
    [
      1
    ],
    [
      2
    ],
    [
      0
    ]
  ]
}

```
I was replace hostname and IP's (---, -.-.-.-)

I'm use your container for this project: [https://github.com/Egregors/youtrack-docker-compose](https://github.com/Egregors/youtrack-docker-compose) in compose file. Looks like challenge url is not working. LE get 502 Bad Gateway (on cold start) or 404.

**Comment by Egregors** [comment]
Fixed it in my case by removing all old certs and restart service twice. I'm actually didn't understand, why standard renewal didn't work well

**Comment by Archcry** [comment]
Same problem here with two new domain names.

**Comment by buchdag** [comment]
@javierojeda94 the only challenge type we're interested in here is `http-01`, if it fails its status will be `invalid` like in @Egregors logs and you'll have a bit more details on the failure (here the server returned a 404 error). 

@Egregors this is not the first time I see someone having an authorization issue cleared up by removing the certs, I'm pretty sure we're having issues with the certs symlinks.

@Archcry it will be hard to provide without logs output. Have you checked https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Invalid-authorizations ?

**Comment by Archcry** [comment]
I found that the files are created (and removed afterwards) and that letsencrypt cannot access my `.well_known` challenge... I tried creating a file in the directory but I cannot access it... The debugging continues. Thanks for the article.

**Comment by gentle9** [comment]
I having the same issues. I created everything new with the two container setup. The Virtualhost is reachable with http and I can access a test.html file in .well-known/acme-challenge/ folder with the virtualhost domain from the internet.
I also can see that the files are created in the acme-challenge folder while the letsencrypt script runs. But I am still receiving the error message that letsencrypt can´t access the file (Code 400: Timeout).

**Comment by buchdag** [comment]
@Archcry Glad it resolved itself even if we could not find the issue.

@gentle9 Yep, you have to be absolutely certain about IPv6 if you put an AAAA record on your domain DNS zone.

**Comment by javierojeda94** [comment]
I solved my problem the same day I reported it on this thread. 

I had a `docker-compose.yml` with all the services inside them (including the one for letsencrypt) and the problem was that when letsencrypt tried to reach the pages, they were still starting.

I separated all the letsencrypt related services (actually all the server related services) into int's own `docker-compose.yml` and it worked perfectly fine

First I started the let's encrypt and then the other apps.

Hopefully this will help another person

**Comment by NicolasDorier** [comment]
Getting this problem randomly, reboot solved it.
@javierojeda94 needing to use two separate docker-compose is a can of worms because now you need to properly start them in the right order and make sure they both run. This is a workaround, but not really applicable in production :(

**Comment by buchdag** [comment]
The certificate generation process only rely on the proxyed container environment variable, wether this container actually run a service or not and this service is ready or not should not have any bearing on it.

You can try to create a certificate for a `busybox` container running nothing but `sleep 3600`, it will work all the same.

**Comment by jlegido** [comment]
Same issue here.

Using, in this example, nginx-proxy + letsencrypt-nginx-proxy-companion + gitlab-ce

The letsencrypt-nginx-proxy-companion logs:

`
{
  "identifier": {
    "type": "dns",
    "value": "gitlab.example.com"
  },
  "status": "invalid",
  "expires": "2018-08-30T15:15:57Z",
  "challenges": [
    {
      "type": "tls-alpn-01",
      "status": "invalid",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/OOo2Ito8JVq8PFt_sWExzspjfsLfJ9NnoBK3KXjpAT8/6713322445",
      "token": "ViR36uPfzIQF7GRAvsnK6qI-8KA9d-Z5cnNQl_hOCWw"
    },
    {
      "type": "dns-01",
      "status": "invalid",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/OOo2Ito8JVq8PFt_sWExzspjfsLfJ9NnoBK3KXjpAT8/6713322446",
      "token": "h_NGoeKp187fMDWJ68lmo5Ko3jcEFltquonUjtcZ0p8"
    },
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:acme:error:unauthorized",
        "detail": "Invalid response from http://gitlab.example.com/.well-known/acme-challenge/v3I-q92tgZsClB_VY3pVB-ZgQXanwJ2RCk9GrmA8LdA: \"\u003chtml\u003e\r\n\u003chead\u003e\u003ctitle\u003e404 Not Found\u003c/title\u003e\u003c/head\u003e\r\n\u003cbody bgcolor=\"white\"\u003e\r\n\u003ccenter\u003e\u003ch1\u003e404 Not Found\u003c/h1\u003e\u003c/center\u003e\r\n\u003chr\u003e\u003ccenter\u003e\"",
        "status": 403
      },
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/OOo2Ito8JVq8PFt_sWExzspjfsLfJ9NnoBK3KXjpAT8/6713322447",
      "token": "v3I-q92tgZsClB_VY3pVB-ZgQXanwJ2RCk9GrmA8LdA",
      "keyAuthorization": "v3I-q92tgZsClB_VY3pVB-ZgQXanwJ2RCk9GrmA8LdA.nEqKsjmuPqIlq8VAZACuH39-vd57v9ZytMS9UH3TxLI",
      "validationRecord": [
        {
          "url": "http://gitlab.example.com/.well-known/acme-challenge/v3I-q92tgZsClB_VY3pVB-ZgQXanwJ2RCk9GrmA8LdA",
          "hostname": "gitlab.example.com",
          "port": "80",
          "addressesResolved": [
            "1.2.3.4"
          ],
          "addressUsed": "1.2.3.4"
        }
      ]
    }
  ],
  "combinations": [
    [
      0
    ],
    [
      2
    ],
    [
      1
    ]
  ]
}
`

The nginx-proxy logs:
`
nginx.1    | gitlab.kedu.cat 66.133.109.36 - - [23/Aug/2018:15:15:58 +0000] "GET /.well-known/acme-challenge/v3I-q92tgZsClB_VY3pVB-ZgQXanwJ2RCk9GrmA8LdA HTTP/1.1" 404 169 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"`

I can pass more information, but this particular container was working fine. I decided to stop the letsencrypt-nginx-proxy-companion, remove all the certificates, and start it again, in order to troubleshoot exactly the same issue with other containers.

**Comment by jlegido** [comment]
And again executing exactly the same command that worked fine this morning to create a container and it's certificates is failing with same behavior reported in [my previous comment](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/341#issuecomment-415459548).

So looks like there are certain conditions where the certificate is no being created because the " /.well-known/acme-challenge/whatever" is not reachable (404).

**Comment by buchdag** [comment]
Can you provide at least the commands / config details of your setup ?

**Comment by jlegido** [comment]
1. Nginx proxy container

`/srv/data/computer/docker/nginx-proxy/network_internal.conf`

```
# These networks are considered "internal"
allow 10.43.3.0/24;
 
# Traffic from all other networks will be rejected
deny all;
```

```
docker run --name nginx-proxy \
  -p 80:80 \
  -p 8443:443 \
  -v /srv/data/computer/docker/nginx-letsencrypt/certs:/etc/nginx/certs:ro \
  -v /srv/data/computer/docker/nginx-proxy/vhost.d:/etc/nginx/vhost.d \
  -v /srv/data/computer/docker/nginx-proxy/network_internal.conf:/etc/nginx/network_internal.conf \
  -v /usr/share/nginx/html \
  -v /var/run/docker.sock:/tmp/docker.sock:ro \
  --label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy \
  -d jwilder/nginx-proxy
```

2. Nginx Let's Encrypt

```
docker run --name nginx-letsencrypt \
  -v /srv/data/computer/docker/nginx-letsencrypt/certs:/etc/nginx/certs:rw \
  --volumes-from nginx-proxy \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -d jrcs/letsencrypt-nginx-proxy-companion
```

3. Test server

```
docker run --name test \
 -e "VIRTUAL_HOST=test.example.com" \
 -e "VIRTUAL_PORT=80" \
 -e "VIRTUAL_PROTO=http" \
 -e "LETSENCRYPT_HOST=test.example.com" \
 -e "LETSENCRYPT_EMAIL=user@example.com" \
 -d php:7-apache
```
Thanks.

**Comment by buchdag** [comment]
Can you try without `network_internal.conf` and with `-p 443:443` on the proxy ?

**Comment by jlegido** [comment]
Ok, I think I found a workaround: removing the "test.example.com" directory under "certs":

`sudo rm -fr /srv/data/computer/docker/nginx-letsencrypt/certs/test.example.com`

After this currently I'm able to create couple of new certificates without any issue.

Thanks for your time and excellent work.

**Comment by buchdag** [comment]
Closing issue due to inactivity.
